### PR TITLE
Add paper Ohkubo et al., Materials Today Physics, 2021

### PR DESCRIPTION
**Pull request by stefanbringuier**
I. Ohkubo, Z. Hou, J. N. Lee, T. Aizawa, M. Lippmaa, T. Chikyow, K. Tsuda, and T. Mori, Realization of Closed-Loop Optimization of Epitaxial Titanium Nitride Thin-Film Growth via Machine Learning, Materials Today Physics 16, 100296 (2021).

Paper presents a method for closed-loop optimization of epitaxial titanium nitride thin-film growth using metal-organic molecular beam epitaxy (MO-MBE) combined with a Bayesian machine-learning technique (using [COMBO python code](https://github.com/tsudalab/combo)). The approach appears to be semi-automated based on the methodology explained.

### CODE REVIEW

**Comment by sgbaird** [comment]
@stefanbringuier, thanks! I'll try to look through it to see what's automated vs. human-in-the-loop.
#15

**Comment by sgbaird** [comment]
@stefanbringuier, I'm kind of swamped atm. Do you have some time to check through these papers to see if it's fully autonomous and if not, what aspects are? If not, I'll swing back to this later 👍

**Comment by stefanbringuier** [comment]
> @stefanbringuier, I'm kind of swamped atm. Do you have some time to check through these papers to see if it's fully autonomous and if not, what aspects are? If not, I'll swing back to this later +1

@sgbaird yes I can do that. Will post back with some details.

**Comment by stefanbringuier** [comment]
So going through this again and the supplemental document, this should be filed as :

:test_tube::microscope::x::computer:| [Realization of closed-loop optimization of epitaxial titanium nitride thin-film growth via machine learning](https://doi.org/10.1016/j.mtphys.2020.100296). Ohkubo, I.; Hou, Z.; Lee, J. N.; Aizawa, T.' Lippmaa, M.; Chikyow, T.; Mori, T. *Materials Today Physics* 2021, 16, 100296.

My reasoning is that although the in-situ reflection high-energy electron diffraction (RHEED) is used for characterization during the film growth, they use the  XRD data step for Bayesian optimization which requires human-in-the-loop.

Initially, when I read the paper I saw in the conclusion:

> The use of in situ RHEED [42] instead of XRD for the characterization of thin films permits more efficient optimization of the thin-film growth parameters and paves the way for automated operation of thin-film growth apparatuses.

and thought it was full automation, but I think the authors intention of this passage is that future work could use RHEED since nothing in their methodolgy, results, or supplemental details indicates this was done.

**Comment by sgbaird** [comment]
Those kinds of nuances can take some time to catch, so thank you for this! 🙏 

I'll get that updated

**Pull request merged**
