### PR TITLE
Add examples of SDL and software tools based on functional data analysis

### PR DESCRIPTION
**Pull request by kiranvad**
* Add digital discovery paper on shape matching for gold nanoparticle retrosynthesis
* Add links to functional data analysis tools for retrosynthesis and phase mapping.

### CODE REVIEW

**Comment by sgbaird** [comment]
Hi @kiranvad, thanks for these contributions! Is the shape retro synthesis paper one that involves any human intervention within or between iterations? Even if not, I still want to be able to highlight partially autonomous labs, in which case I'll need to think a bit about the organization and format.

**Comment by kiranvad** [comment]
Hi @sgbaird, the only human intervention is in making the stock solutions (of the same concentrations) and transferring the well plates between the plate reader and Opentrons. So yes, characterization is included in the loop.

**Comment by kiranvad** [comment]
yes, that is correct. I should've been more clear.

**Comment by sgbaird** [comment]
All good. Thank you!

**Pull request closed without merging**
