### PR TITLE
Add [Self-Driving Labs in academia]

### PR DESCRIPTION
**Pull request by Yujikaiya**
Add Self-Driving Labs in academia

2023: https://arxiv.org/abs/2304.13927
2020: https://doi.org/10.1063/5.0020370

Two self-driving lab examples in Japan. One was published in very early phase of SDL and the other is one of the latest example.

### CODE REVIEW

**Comment by sgbaird** [comment]
Thanks for the contribution!

It's great to see SDLs applied to Li-O2 and other battery systems (I used to work with Li-O2 batteries). I found a picture of the hardware in the SI of [DOI: 10.1038/s41598-019-42766-x](https://dx.doi.org/10.1038/s41598-019-42766-x) (Fig S2), which helped me to get a better idea of the setup. Is there any human intervention during the experimental campaign?



For example, was there any human intervention during the campaign that generated the data shown in Fig 5 of [DOI: 10.1038/10.48550/arXiv.2304.13927](https://dx.doi.org/10.48550/arXiv.2304.13927)?

image

Aside: http://nims-os.to/ (linked to in the abstract of [the 2023 article](https://arxiv.org/abs/2304.13927)) shows `nims-os.to’s server IP address could not be found.`

**Comment by Yujikaiya** [comment]
I checked with the author. Everything is automatic except for the mother solution preparation and plate setting.
This tweet shows how the system works! (Both software and hardware)
https://twitter.com/kojitsuda/status/1652198799627153408

**Comment by sgbaird** [comment]
@Yujikaiya great, thanks for checking! By plate setting, do you mean a one-time task prior to starting the experimental campaign?

**Comment by Yujikaiya** [comment]
Yes, plate setting is only a one-time task prior to starting the experimental campaign.

**Comment by sgbaird** [comment]
@Yujikaiya great! Just merged :) Thanks again!

**Comment by sgbaird** [comment]
Aside: http://nims-os.to/ (linked to in the abstract of [the 2023 article](https://arxiv.org/abs/2304.13927)) shows `nims-os.to’s server IP address could not be found.`

**Pull request merged**
